select
--L1.description
S2.REGION AS S2_REGION
,S2.ADDRESS3 AS S2_AREA
,S1.DESCRIPTION AS S1_LOCATION
,L1.CINAME AS L1_HARDWARE


FROM ci L1
LEFT OUTER JOIN CIRELATION L12 ON L12.TARGETCI=L1.CINUM AND L12.relationnum='IP-АДРЕС ПРИСВОЕН ШАССИ'
LEFT OUTER JOIN CI L2 ON L2.CINUM=L12.SOURCECI
LEFT OUTER JOIN CIRELATION L24 ON L24.TARGETCI=L2.CINUM AND L24.relationnum='BRIDGE DOMAIN ИСПОЛЬЗУЕТ IP-АДРЕС'
LEFT OUTER JOIN CI L4 ON L4.CINUM=L24.SOURCECI
LEFT OUTER JOIN CIRELATION L43 ON L43.SOURCECI=L4.CINUM AND L43.relationnum='ИСПОЛЬЗУЕТ ИНТЕРФЕЙС'
LEFT OUTER JOIN CI L3 ON L3.CINUM=L43.TARGETCI
LEFT OUTER JOIN CIRELATION L46 ON L46.TARGETCI=L4.CINUM
LEFT OUTER JOIN CI L6 ON L6.CINUM=L46.SOURCECI
LEFT OUTER JOIN CIRELATION L65 ON L65.SOURCECI=L6.CINUM and L65.relationnum='ВИРТ. КАНАЛ ИСПОЛЬЗУЕТ КАНАЛ'
LEFT OUTER JOIN CI L5 ON L5.CINUM=L65.TARGETCI
LEFT OUTER JOIN CIRELATION L76 ON L76.TARGETCI=L6.CINUM and L76.relationnum='ВХОДЯТ ВИРТУАЛЬНЫЕ КАНАЛЫ'
LEFT OUTER JOIN CI L7 ON L7.CINUM=L76.SOURCECI
LEFT OUTER JOIN LOCATIONS S1 ON S1.SITEID=L1.CILOCATION
LEFT OUTER JOIN ADDRESS S2 ON S2.ADDRESS2=S1.DESCRIPTION

where L1.CLASSSTRUCTUREID IN ('1045','1046') -- ROUTER, SWITCH
group by
S2.REGION
,S2.ADDRESS3
,S1.DESCRIPTION
,L1.CINAME